/* tslint:disable */
/* eslint-disable */
/**
 * flexCharge-service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AdditionalField
 */
export interface AdditionalField {
    /**
     * 
     * @type {string}
     * @memberof AdditionalField
     */
    key?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdditionalField
     */
    value?: string | null;
}
