/* tslint:disable */
/* eslint-disable */
/**
 * flexCharge-service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BillingInformation
 */
export interface BillingInformation {
    /**
     * 
     * @type {string}
     * @memberof BillingInformation
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof BillingInformation
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof BillingInformation
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BillingInformation
     */
    country: string;
    /**
     * 
     * @type {string}
     * @memberof BillingInformation
     */
    countryCode: string;
    /**
     * 
     * @type {string}
     * @memberof BillingInformation
     */
    addressLine1: string;
    /**
     * 
     * @type {string}
     * @memberof BillingInformation
     */
    addressLine2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BillingInformation
     */
    state?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BillingInformation
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof BillingInformation
     */
    zipcode: string;
}
