/* tslint:disable */
/* eslint-disable */
/**
 * flexCharge-service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Merchant
 */
export interface Merchant {
    /**
     * 
     * @type {string}
     * @memberof Merchant
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Merchant
     */
    id?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Merchant
     */
    mcc?: number;
    /**
     * 
     * @type {string}
     * @memberof Merchant
     */
    country?: string | null;
}
