/* tslint:disable */
/* eslint-disable */
/**
 * flexCharge-service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OrderItem
 */
export interface OrderItem {
    /**
     * 
     * @type {string}
     * @memberof OrderItem
     */
    sku?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrderItem
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrderItem
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof OrderItem
     */
    amount?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderItem
     */
    discountAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderItem
     */
    tax?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderItem
     */
    discountType?: string | null;
    /**
     * 
     * @type {number}
     * @memberof OrderItem
     */
    quantity?: number;
}
