/* tslint:disable */
/* eslint-disable */
/**
 * flexCharge-service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PaymentMethodLast4Digits
 */
export interface PaymentMethodLast4Digits {
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodLast4Digits
     */
    holderName: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodLast4Digits
     */
    cardType: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodLast4Digits
     */
    cardBrand: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodLast4Digits
     */
    cardCountry: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodLast4Digits
     */
    cardIssuer?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodLast4Digits
     */
    cardLevel?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodLast4Digits
     */
    cardFingerprint?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PaymentMethodLast4Digits
     */
    expirationMonth: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentMethodLast4Digits
     */
    expirationYear: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodLast4Digits
     */
    cardBinNumber: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodLast4Digits
     */
    cardLast4Digits: string;
}
