/* tslint:disable */
/* eslint-disable */
/**
 * flexCharge-service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RefundRequest
 */
export interface RefundRequest {
    /**
     * 
     * @type {string}
     * @memberof RefundRequest
     */
    mid?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RefundRequest
     */
    amountToRefund?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RefundRequest
     */
    isPartialRefund?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RefundRequest
     */
    transactionId?: string | null;
}
