/* tslint:disable */
/* eslint-disable */
/**
 * flexCharge-service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Subscription
 */
export interface Subscription {
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    subscriptionId: string;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    interval: string;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    price: string;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    paymentNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    totalPayments?: string | null;
}
